/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as mainLayoutRouteImport } from './routes/(main)/_layout'
import { Route as mainLayoutIndexRouteImport } from './routes/(main)/_layout/index'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout/users'
import { Route as AdminLayoutDashboardRouteImport } from './routes/admin/_layout/dashboard'
import { Route as mainLayoutContactsRouteImport } from './routes/(main)/_layout/contacts'
import { Route as mainLayoutBlogRouteImport } from './routes/(main)/_layout/blog'
import { Route as mainLayoutAboutRouteImport } from './routes/(main)/_layout/about'

const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const mainLayoutRoute = mainLayoutRouteImport.update({
  id: '/(main)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const mainLayoutIndexRoute = mainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainLayoutRoute,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDashboardRoute = AdminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const mainLayoutContactsRoute = mainLayoutContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutBlogRoute = mainLayoutBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutAboutRoute = mainLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => mainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/about': typeof mainLayoutAboutRoute
  '/blog': typeof mainLayoutBlogRoute
  '/contacts': typeof mainLayoutContactsRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/': typeof mainLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminIndexRoute
  '/about': typeof mainLayoutAboutRoute
  '/blog': typeof mainLayoutBlogRoute
  '/contacts': typeof mainLayoutContactsRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/': typeof mainLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)/_layout': typeof mainLayoutRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/(main)/_layout/about': typeof mainLayoutAboutRoute
  '/(main)/_layout/blog': typeof mainLayoutBlogRoute
  '/(main)/_layout/contacts': typeof mainLayoutContactsRoute
  '/admin/_layout/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRoute
  '/(main)/_layout/': typeof mainLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/admin/'
    | '/about'
    | '/blog'
    | '/contacts'
    | '/admin/dashboard'
    | '/admin/users'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/about'
    | '/blog'
    | '/contacts'
    | '/admin/dashboard'
    | '/admin/users'
    | '/'
  id:
    | '__root__'
    | '/(main)/_layout'
    | '/admin/_layout'
    | '/admin/'
    | '/(main)/_layout/about'
    | '/(main)/_layout/blog'
    | '/(main)/_layout/contacts'
    | '/admin/_layout/dashboard'
    | '/admin/_layout/users'
    | '/(main)/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainLayoutRoute: typeof mainLayoutRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_layout': {
      id: '/(main)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_layout/': {
      id: '/(main)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainLayoutIndexRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dashboard': {
      id: '/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/(main)/_layout/contacts': {
      id: '/(main)/_layout/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof mainLayoutContactsRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/blog': {
      id: '/(main)/_layout/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof mainLayoutBlogRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/about': {
      id: '/(main)/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof mainLayoutAboutRouteImport
      parentRoute: typeof mainLayoutRoute
    }
  }
}

interface mainLayoutRouteChildren {
  mainLayoutAboutRoute: typeof mainLayoutAboutRoute
  mainLayoutBlogRoute: typeof mainLayoutBlogRoute
  mainLayoutContactsRoute: typeof mainLayoutContactsRoute
  mainLayoutIndexRoute: typeof mainLayoutIndexRoute
}

const mainLayoutRouteChildren: mainLayoutRouteChildren = {
  mainLayoutAboutRoute: mainLayoutAboutRoute,
  mainLayoutBlogRoute: mainLayoutBlogRoute,
  mainLayoutContactsRoute: mainLayoutContactsRoute,
  mainLayoutIndexRoute: mainLayoutIndexRoute,
}

const mainLayoutRouteWithChildren = mainLayoutRoute._addFileChildren(
  mainLayoutRouteChildren,
)

interface AdminLayoutRouteChildren {
  AdminLayoutDashboardRoute: typeof AdminLayoutDashboardRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutDashboardRoute: AdminLayoutDashboardRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainLayoutRoute: mainLayoutRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
